---
title: "The Jo Lab - Open Positions"
format:
  html:
    title-block-style: none
    page-layout: full
    css: style.css
    anchor-sections: false
---


<center>[**Open Positions**]{style="font-size: 24px;"}</center>

------------------------------------------------------------------------

<p style="text-align: justify; color: black; font-size: 22px; margin-top: 0; margin-bottom: 10;">PhD Position in the Role of Cell Identity in Shaping Plant Stress Responses</p>
<p style="text-align: justify; color: #666; font-size: 18px; margin-top: 0; margin-bottom: 10;">
I'm very excited to announce that the Jo Lab is hiring our FIRST EVER PhD candidate!
Passionate about plant stress responses, molecular biology, and bioinformatics? Join our lab as PhD candidate and investigate why unique plant cells respond so differently to the same environmental stimuli. You’ll gain hands-on experience with cutting-edge single-cell genomics and functional genomics to uncover the drivers of plant transcriptional responses to the environment. If you're eager to drive discovery in plants, join us at UU Plants! </p>
<p style="text-align: justify; color: #666; font-size: 18px; margin-top: 0; margin-bottom: 10;">
More Info: <a href=https://www.uu.nl/en/organisation/working-at-utrecht-university/jobs/phd-position-in-the-role-of-cell-identity-in-shaping-plant-stress-responses>https://www.uu.nl/en/organisation/working-at-utrecht-university/jobs/phd-position-in-the-role-of-cell-identity-in-shaping-plant-stress-responses</a>
</p>
<p style="text-align: justify; color: #666; font-size: 18px; margin-top: 0; margin-bottom: 10;">
Deadline: 10 May 2026
</p>

------------------------------------------------------------------------

<p style="text-align: justify; color: black; font-size: 22px; margin-top: 0; margin-bottom: 10;">Student internships</p>
<p style="text-align: justify; color: #666; font-size: 18px; margin-top: 0; margin-bottom: 10;">
Our group is always open for masters or bachelors internships! We can provide internships that will allow you to explore different aspects of functional genomics, epigenetics and bioinformatics in plants. If you are eager to learn, please email me (l.jo@uu.nl), and we can discuss potential projects.</p>

------------------------------------------------------------------------

<p style="text-align: justify; color: black; font-size: 22px; margin-top: 0; margin-bottom: 10;">Other opportunities</p>
<p style="text-align: justify; color: #666; font-size: 18px; margin-top: 0; margin-bottom: 10;">
We are always interested in hearing from motivated researchers who want to explore different aspects of functional genomics and epigenetics to understand plant environmental responses. I am open to discuss possibilities to support your application for personal postdoctoral grants. Some possibilities include: ERC Marie Skłodowska-Curie Actions, EMBO Fellowship and the NWO Veni grants.
If you would like to discuss possibilities, please send me your CV and motivation letter to l.jo@uu.nl.</p>
